"""
This Application is to monitor attendance for events
"""
import datetime
import uuid


# HELPER FUNCTION
def generate_event_no():
    return uuid.uuid4().hex


event = {
    'date': '',  # Date and Time
    'location': '',  # Emirates
    'registrants': '',  # person
    'event_no': '',  # Autogenerated Int
}

registrant = {
    'name': '',  # Name
    'registration_no': '',  # YYMMDD-SR 000-999
}

attendance = {
    'time': '',  # Time
    'registration_no': ''  #
}

# -----------------------------------------
# SETUP EVENT
# -----------------------------------------

event_date = input("Event Date and Time: ")
event_location = input("Location: ")

event_registrants = []
# [name, registration_no]
while True:
    event_registrant = input("Enter Registrant or type q to stop: ")
    if event_registrant.lower() == 'q':
        break
    event_registrants.append([event_registrant, f'{len(event_registrants)+1:03}'])

event = {
    'date': datetime.datetime.strptime(event_date, '%y%m%d %H:%M'),  # Date and Time
    'location': event_location,  # Emirates
    'registrants': event_registrants,  # person
    'event_no': generate_event_no(),  # Autogenerated Int
}

print(event)
