"""
This Application is to monitor attendance for events
"""
import datetime
import uuid
import json
import os


# HELPER FUNCTION
def generate_event_no():
    return uuid.uuid4().hex


def save_config(event):
    event['date'] = f'{event["date"]:%y%m%d %H:%M}'
    with open('config.json', 'w') as outfile:
        json.dump(event, outfile)


def get_config():
    if not os.path.isfile('config.json'):
        return None
    with open('config.json') as infile:
        data = json.loads(infile.read())
        data['date'] = datetime.datetime.strptime(data['date'], '%y%m%d %H:%M')
    return data


def setup_event():
    event_date = input("Event Date and Time: ")
    event_location = input("Location: ")

    event_registrants = []
    # [name, registration_no]
    while True:
        event_registrant = input("Enter Registrant or type q to stop: ")
        if event_registrant.lower() == 'q':
            break
        event_registrants.append([event_registrant, f'{len(event_registrants)+1:03}'])

    event = {
        'date': datetime.datetime.strptime(event_date, '%y%m%d %H:%M'),  # Date and Time
        'location': event_location,  # Emirates
        'registrants': event_registrants,  # person
        'event_no': generate_event_no(),  # Autogenerated Int
    }

    return event


attendance = {
    'time': '',  # Time
    'registration_no': ''  #
}

# -----------------------------------------
# SETUP EVENT
# -----------------------------------------

event = get_config()

if event is None:
    event = setup_event()
    save_config(event)

print(event)
